version: '3.8'

services:
  db:
    image: postgres:15
    container_name: agrichain-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: joko1453
      POSTGRES_DB: agribatch
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d agribatch"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./Backend
    container_name: agrichain-backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DB_HOST=db
      - DB_PORT=5432 # Connects to PostgreSQL inside the docker network on 5432
      - DB_NAME=agribatch
      - DB_USER=postgres
      - DB_PASSWORD=joko1453
      - JWT_SECRET=agribatch_super_secret_key_2026
      - JWT_EXPIRES_IN=24h
    env_file:
      - ./Backend/.env
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./Frontend
    container_name: agrichain-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  pgdata:
